.\" This man page is Copyright (C) 2003, 2010 Lennert Buytenhek.
.\" Permission is granted to distribute possibly modified copies
.\" of this page provided the header is included verbatim,
.\" and in case of nontrivial modification author and date
.\" of the modification is added to the header.
.TH iv_quit 3 2010-08-15 "ivykis" "ivykis programmer's manual"
.SH NAME
iv_quit \- signal ivykis to exit the main loop
.SH SYNOPSIS
.B #include <iv.h>
.sp
.BI "void iv_quit(void);"
.br
.SH DESCRIPTION
.B iv_quit
signals ivykis to exit the current thread's main loop.
.PP
If called from any callback function,
.B iv_quit
will cause the
.BR iv_main (3)
function called from the current thread to return.  It is not meant
to be used casually.
.SH "SEE ALSO"
.BR ivykis (3),
.BR iv_examples (3)
