.\" This man page is Copyright (C) 2003 Lennert Buytenhek.
.\" Permission is granted to distribute possibly modified copies
.\" of this page provided the header is included verbatim,
.\" and in case of nontrivial modification author and date
.\" of the modification is added to the header.
.TH iv_wrappers 3 2003-03-29 "ivykis" "ivykis programmer's manual"
.SH NAME
iv_wrappers \- wrapper functions for ivykis file descriptor handling
.SH SYNOPSIS
.B #include <iv.h>
.sp
.BI "int iv_accept(struct iv_fd * " fd ", struct sockaddr * " addr ", socklen_t * " addrlen ");"
.br
.BI "int iv_connect(struct iv_fd * " fd ", struct sockaddr * " addr ", socklen_t " addrlen "); "
.sp
[...] et cetera.
.SH DESCRIPTION
It is not permitted to use regular I/O primitives in combination with
ivykis file descriptors.  For example, one cannot use the ordinary
.BR read (2)
and
.BR write (2)
primitives.  ivykis needs to detect when a certain file descriptor is
no longer active, and therefore it needs to catch the return value of
all I/O done on the file descriptor.
.PP
ivykis provides wrapped analogues for most of the I/O primitives
available.  These wrapped versions have a name that starts with
.B iv_,
and take as first argument a
.B 'struct iv_fd *fd'
instead of an
.B 'int fd'.
A full list can be found in the header file iv.h.
.SH "SEE ALSO"
.BR ivykis (3),
.BR iv_examples (3)
